services:
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: etl-app
    image: etl-app:latest  # Replace with the actual image and tag
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - mysql  # Ensure MySQL server is started before the application
    volumes:
      - app_data:/app/data
volumes:
    app_data:  # Define the app_data volume
    db:
